# Generated by Django 5.1.2 on 2024-11-04 14:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=64, verbose_name='任务ID')),
                ('job_name', models.CharField(max_length=64, verbose_name='任务名称')),
                ('job_status', models.CharField(max_length=64, verbose_name='任务状态')),
                ('job_cron', models.CharField(max_length=64, verbose_name='任务cron')),
                ('job_func', models.CharField(max_length=64, verbose_name='任务函数')),
                ('job_args', models.CharField(max_length=64, verbose_name='任务参数')),
                ('job_kwargs', models.CharField(max_length=64, verbose_name='任务kwargs')),
                ('job_trigger', models.CharField(default='CronTrigge', max_length=64, verbose_name='任务触发器')),
                ('job_next_run_time', models.CharField(max_length=64, verbose_name='下次运行时间')),
                ('job_success_count', models.IntegerField(default=0, verbose_name='成功次数')),
                ('job_fail_count', models.IntegerField(default=0, verbose_name='失败次数')),
                ('job_start_time', models.CharField(max_length=64, verbose_name='开始时间')),
                ('job_end_time', models.CharField(max_length=64, verbose_name='结束时间')),
                ('job_create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('job_update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '任务信息',
                'verbose_name_plural': '任务信息',
                'db_table': 'job_info',
            },
        ),
    ]
