# Generated by Django 5.1.2 on 2024-11-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinfo',
            name='job_args',
            field=models.FileField(upload_to='', verbose_name='任务参数'),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='job_create_time',
            field=models.DateTimeField(default='2024-11-04 15:42:24', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='job_kwargs',
            field=models.FileField(upload_to='', verbose_name='任务kwargs'),
        ),
    ]
