# Generated by Django 5.1.2 on 2024-11-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_jobinfo_job_args_alter_jobinfo_job_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinfo',
            name='job_args',
            field=models.TextField(verbose_name='任务参数'),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='job_create_time',
            field=models.DateTimeField(default='2024-11-04 15:44:07', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='job_kwargs',
            field=models.TextField(verbose_name='任务kwargs'),
        ),
    ]
